### ISSUE TITLE
Problems in “dreme-py3” and “Making cut point matrix”

### ISSUE THREAD

**Issue by yannnnLi** [fl-yu/CUT-RUNTools-2.0#33]
Hello Fulong,
There are 2 error when I run bulk CUT&RUNTools2.1 pipeline with example data:

![image](https://user-images.githubusercontent.com/46277338/147386916-2645c278-6500-4dca-8f16-ceb9b81e0086.png)
![image](https://user-images.githubusercontent.com/46277338/147386973-23c37b8a-8921-4b6f-baae-6d554809c478.png)
[38.err.txt](https://github.com/fl-yu/CUT-RUNTools-2.0/files/7775939/38.err.txt)
[38.out.txt](https://github.com/fl-yu/CUT-RUNTools-2.0/files/7775940/38.out.txt)

Could you give some advice to me?
Thanks for your kindness.
Yan

**Comment by fl-yu** [comment]
Hi Yan, 
These two issues seem no harm to your real data in my view. The first one maybe related to the incomplete installation of meme but it should work well for data processing. The second one maybe caused by the test data is too small to calculate cut matrix right to that motif. Hope this is helpful.

**Comment by yannnnLi** [comment]
Dear Fulong
Thanks for your reply.
