### ISSUE TITLE
SLURM opal error

### ISSUE THREAD

**Issue by garci1294** [fl-yu/CUT-RUNTools-2.0#7]
Hello @fl-yu,

Do you have any suggestions on how to run this pipeline on an HPC using SLURM?

I keep on getting OMPI errors. For example: OPAL ERROR: Not initialized in file pmix2x_client.c at line 112

Any help is greatly appreciated.

Thank you,
Jesus

**Comment by fl-yu** [comment]
Hi Jesus

Our first version perfectly matches with SLURM system you may want to use it.

In CUT&RUNTools2.0, we do not support job scheduler systems such as SLURM directly to accommodate more diverse users. 
I think you could first request resources, then you should be running the pipeline like on a single computer then.

**Comment by garci1294** [comment]
Thank you @fl-yu! This makes sense.

**Comment by kindln** [comment]
Hi. FYI, on our system the problem turned out to be that all pre-built versions of MEME, such as those you'd find on docker hub or with a conda install, were built with MPI enabled. I also kept getting the MPI/OPAL errors due to conflicts with SLURM, so the solution for us was to download and build the MEME suite manually, because MPI isn't enabled by default. The pre-built ones must have specified the flags to explicitly enable it. Just sharing my experience.

**Comment by fl-yu** [comment]
Hi Kindln! Thank you for your sharing experience with MEME. I believe it would be helpful for people who are in trouble with MEME installation.
